### PR TITLE
Add queueMicrotask support

### PR DESCRIPTION
**Pull request by tinchoz49**

### CODE REVIEW

**Comment by tinchoz49** [comment]
@calvinmetcalf should we also include a Promise type? what do you think? `Promise.resolve().then(func)`

**Comment by calvinmetcalf** [comment]
sure, though it should probably be:

```js
function throwError (error) {
  throw error;
}

Promise.resolve().then(func).catch(function (error) {
  setTimeout(throwError, 0, error);
})
```

**Comment by tinchoz49** [comment]
You right, Promise seems to be working but I get test error in: 

```
not ok 7 3rd schedualed happens after the error
not ok 8 recursive one is 4th
not ok 10 error is third
```

The test 7 makes sense, since we are scheduling the error with setTimeout the next immediate with Promise will be executed before than the timeout but I don't know how solve that problem, we cannot throw the error inside a promise. 

Maybe we can just add the queueMicrotask for now.

**Comment by calvinmetcalf** [comment]
yeah the promise one causes the error to be a tick late, so yeah scrub that one and we can do the microQueue

**Comment by calvinmetcalf** [comment]
ok I'll take a look tommorw

**Comment by calvinmetcalf** [comment]
(didn't mean to close)

**Comment by tinchoz49** [comment]
don't worry thanks!

**Pull request merged**
